[book]
authors = ["BilalM04"]
language = "en"
multilingual = false
src = "src"
title = "Software Requirements Specification for Projectile"
[output.html]
smart-punctuation = true
mathjax-support = true
